# Travis Continuous Integration script for travis-ci.org
dist: trusty

# Runs all unit tests and check for broken links
language: java

jdk:
  - oraclejdk8

# Install ruby to get gem command
before_install:
  - sudo apt-add-repository -y ppa:brightbox/ruby-ng
  - sudo apt-get -y update
  - sudo apt-get -y install ruby-full

# Install awesome_bot for README.md broken link checking
before_script:
  - gem install awesome_bot

# Run broken link check and tests
script:
  - awesome_bot README.md --allow-dupe --allow-redirect
  - gradle test
