language: python
python: 3.6
sudo: false
install:
  - pip3 install doc8 sphinx
script:
  - make html 2> stderr.log
  - cat stderr.log
  - doc8 --ignore D001 --ignore-path build
  # fail the build for any stderr output
  - if [ -s "stderr.log" ]; then false; fi
notifications:
  email: false
